Fix grammatical errors
line/line-sdk-android pull request #88
Opened 2020-09-01 06:42 UTC by androiddevnotes

2020-09-01 06:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/line/line-sdk-android?pullRequest=88) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/line/line-sdk-android?pullRequest=88) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/line/line-sdk-android?pullRequest=88) it.</sub>

2020-09-04 06:24 UTC, marshallgunnell requested changes
Thanks for finding these issues! We'd like to make all of the changes except one.

2020-09-04 06:24 UTC, marshallgunnell commented on README.md
> +For more information, refer to the [LINE SDK for the Android guide](https://developers.line.biz/en/docs/android-sdk/) on the [LINE Developers site](https://developers.line.biz).
```suggestion
For more information, refer to the [LINE SDK for Android guide](https://developers.line.biz/en/docs/android-sdk/) on the [LINE Developers site](https://developers.line.biz).
```

Let's leave as-is. the product is "LINE SDK for Android", so it's right to say `the [LINE SDK for Android guide]`

2020-09-06 12:27 UTC, androiddevnotes commented
> Thanks for finding these issues! We'd like to make all of the changes except one.

I have added another commit as per your suggestion.

2021-04-09 03:00 UTC, merged